# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: deploy

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: do-server
    steps:
      - uses: actions/checkout@v4
      - name: create env
        run: |
          touch /home/trimo/actions-runner/src/trimo-wa-bot/trimo-wa-bot/.env
          echo 'DATABASE_URL=${{secrets.DATABASE_URL}}' > /home/trimo/actions-runner/src/trimo-wa-bot/trimo-wa-bot/.env
      - name: Install Modules
        run: npm ci
      # - name: Add browser args
      #   run: sed -i '304 i browserArgs.push("--no-sandbox");' /home/trimo/actions-runner/src/trimo-wa-bot/trimo-wa-bot/node_modules/whatsapp-web.js/src/Client.js
      - name: Generate prisma schema
        run: npx prisma generate
      - name: change dir
        run: cd /home/trimo/actions-runner/src/trimo-wa-bot/trimo-wa-bot
      - run: pm2 restart 0
